### ISSUE TITLE
EnTK script fails while running on any XSEDE resource with "resource allocation failed"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#333]
Unsure what else I can provide since there are no logs (or even a sandbox) on the agent side. 
Trying to run on Comet and Bridges. 
Terminal output is below
```
2019-04-11 15:29:44,863: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2019-04-11 15:29:44,864: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2019-04-11 15:29:53,405: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2019-04-11 15:29:53,405: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2019-04-11 15:29:53,475: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot is now active
2019-04-11 15:29:53,475: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: Cannot proceed. Resource allocation ended up in FAILED
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 311, in run
    raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
EnTKError: Cannot proceed. Resource allocation ended up in FAILED
2019-04-11 15:29:53,476: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2019-04-11 15:29:53,476: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : DEBUG   : WFprocessor process already terminated
```
`grep ETTOR *log` on the client side gives:
```
pmgr.0000.launching.0.child.log:2019-04-11 15:29:53,402: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
radical.entk.appmanager.0000.log:2019-04-11 15:29:53,475: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: Cannot proceed. Resource allocation ended up in FAILED
radical.entk.resource_manager.0000.log:2019-04-11 15:29:53,405: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
re.session.mcewan.engr.rutgers.edu.scm177.017997.0007.log:2019-04-11 15:29:58,632: re.session.mcewan.engr.rutgers.edu.scm177.017997.0007: MainProcess                     : MainThread     : ERROR   : failed to fet profile for pilot.0000
```

This seems to be at the EnTK layer, because I _think_ I'm able to run the RP examples on Comet?

`radical-stack` is:

```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.60.0@devel
  radical.entk         : 0.7.16-0.7.15-12-g98ea7f1@feature-suspend_resume
  radical.pilot        : 0.60.0-v0.60.0@devel
  radical.saga         : 0.60.0
  radical.utils        : 0.60.0
```

Happy to help debug. Thanks.

**Comment by andre-merzky** [comment]
You will likely find an exception trace in `pmgr.0000.launching.0.child.log` which should help you further.  If not, can you please attach that file?  Thanks!

**Comment by SrinivasMushnoori** [comment]
I see the following traceback:
```
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 488, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 654, in _start_pilot_bulk
    js_tmp  = rs.job.Service(js_url, session=self._session)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/job/service.py", line 116, in __init__
    url, session, ttype=_ttype)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/base.py", line 105, in __init__
    **kwargs)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/adaptors/cpi/decorators.py", line 62, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/adaptors/shell/shell_job.py", line 478, in init_instance
    self.initialize ()
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/adaptors/shell/shell_job.py", line 529, in initialize
    raise rse.NoSuccess ("host setup failed (%s): (%s)" % (ret, out))
NoSuccess: host setup failed (1): (mkdir: cannot create directory `/home/scm177': Permission denied
) (/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/adaptors/shell/shell_job.py +529 (initialize)  :  raise rse.NoSuccess ("host setup failed (%s): (%s)" % (ret, out)))
```

File is attached [here.](https://github.com/radical-cybertools/radical.entk/files/3070583/pmgr.0000.launching.0.child.zip)

**Comment by SrinivasMushnoori** [comment]
Actually scratch that about being able to run from RP, [the simple bag-of-tasks example](https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/docs/simple_bot.py) fails as well.

**Comment by andre-merzky** [comment]
Can you please let me know the output of `radical-stack`, the exact command line you run for the example, and the host you are working on?  Thanks!

**Comment by SrinivasMushnoori** [comment]
Hey, apologies: I should have in that post itself, not sure why I didn't. Here you go:
`radical-stack` is:
```

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.60.0@devel
  radical.entk         : 0.7.16-0.7.15-12-g98ea7f1@feature-suspend_resume
  radical.pilot        : 0.60.0-v0.60.0@devel
  radical.saga         : 0.60.0
  radical.utils        : 0.60.0
```

Command line:
`$ RADICAL_PILOT_VERBOSE=DEBUG python simple_bot.py`

And the resource is Comet. I'm using `xsede.comet_ssh` but I get the following error:

```
Traceback (most recent call last):
  File "simple_bot.py", line 72, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 103, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/pilot/session.py", line 1022, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/utils/pty_shell.py", line 244, in __init__
    interactive=self.interactive)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 201, in initialize
    self._initialize_pty(info['pty'], info)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 422, in _initialize_pty
    raise ptye.translate_exception (e)
radical.saga.exceptions.AuthenticationFailed: prompted for unknown password (Password: ) (/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/saga/utils/pty_shell_factory.py +321 (_initialize_pty)  :  % match))

```

Now here's the thing. I'm not even able to log in because of the above "prompted for unknown password" via RP. But I'm able to gsissh just fine.

**Comment by andre-merzky** [comment]
thanks - let me try to reproduce this.

**Comment by andre-merzky** [comment]
This will be addressed in RP.

**Comment by andre-merzky** [comment]
@SrinivasMushnoori : can you please check if you are hitting file system quota?

**Comment by SrinivasMushnoori** [comment]
Sorry I missed this. I will check today and get back to you.

**Comment by SrinivasMushnoori** [comment]
@andre-merzky sorry for the late response on this, but experiments have resumed. This issue has not been resolved in the latest stack. I can confirm that I am not hitting the file system quota.

**Comment by SrinivasMushnoori** [comment]
As discussed via slack, I have:
1) deleted the VE and run the ENTK example to see if the ve is created on its own
2) manually create a VE after loading the appropriate modules if unsuccessful.

Neither work, it actually fails with the same error:

```Traceback (most recent call last):
 File "dummy_exchange.py", line 372, in <module>
   exchange.execute()
 File "dummy_exchange.py", line 90, in execute
   self.run()
 File "/home/scm177/VirtualEnvs/RCT_TEST/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 313, in run
   raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource allocation ended up in FAILED```

**Comment by SrinivasMushnoori** [comment]
Resolved.

**Comment by SrinivasMushnoori** [comment]
Apologies @andre-merzky and @mturilli this issue has re-emerged.
I did not change the stack, but there was a power failure in my building for a split second this morning that caused my desktop to shut down. After turning it on again, loading my environments and such like I always do, I tried to run and it failed with the above error. 

I have attempted to run it not only on XSEDE but even localhost, where it also fails.

My apologies: I do not recollect exactly what files you need to diagnose this, but here is my stack:
```
/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.60.0@devel
  radical.entk         : 0.70.0-v0.70.0@master
  radical.pilot        : 0.62.0
  radical.saga         : 0.62.0
  radical.utils        : 0.62.0
```
I run after enabling:
```export RADICAL_LOG_LVL="DEBUG"
export RADICAL_LOG_TGT="radical.log"
export RADICAL_PROFILE="TRUE"```
And here is the `radical.log` [file](https://github.com/radical-cybertools/radical.entk/files/3478839/radical.log)
)

**Comment by andre-merzky** [comment]
Thanks Srininvas.  Can you please attach the client session tarball to the ticket?

**Comment by SrinivasMushnoori** [comment]
Sure, [here you go.](https://github.com/radical-cybertools/radical.entk/files/3479198/sandbox.zip)

**Comment by andre-merzky** [comment]
Srinivas, can you please update to the last release for all RCT modules?  Easiest would be to just create  a new virtualenv and do a `pip install radical.entk` - that will pull the releases for all modules.  You should then be on something like
```
  radical.entk         : 0.70.0
  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```
or so.  Please run your test then *twice* (the first run will likely fail for different reasons), and pack both local and pilot sandbox again.  Thanks, sorry for making you hop through these steps again...

**Comment by SrinivasMushnoori** [comment]
Creating a new virtual env and running `pip install radical.entk` fails with:

```
Exception:
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/home/scm177/VirtualEnvs/radical_stack/local/lib/python2.7/site-packages/pip/util.py", line 556, in untar_file
    path = os.path.join(location, fn)
  File "/home/scm177/VirtualEnvs/radical_stack/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)

Storing debug log for failure in /home/scm177/.pip/pip.log

```

**Comment by mturilli** [comment]
Is this on a linux machine with python 2?

**Comment by SrinivasMushnoori** [comment]
Yes.

```
(radical_stack)scm177@mcewan:~/RADICAL-LAB/RADICAL_ENTK_STACK/radical.entk$ which python                                                                                    
/home/scm177/VirtualEnvs/radical_stack/bin/python
(radical_stack)scm177@mcewan:~/RADICAL-LAB/RADICAL_ENTK_STACK/radical.entk$ python -V
Python 2.7.14

```

**Comment by mturilli** [comment]
Thanks. Can you tell me what the following returns? `$ echo LANG=$LANG`

**Comment by SrinivasMushnoori** [comment]
Sure:
```
(radical_stack)scm177@mcewan:~/RADICAL-LAB/RADICAL_ENTK_STACK/radical.entk$  echo LANG=$LANG
LANG=en_US.UTF-8

```

**Comment by mturilli** [comment]
Puzzling. Could you try the following:
```
$ python
>>> import sys; sys.getfilesystemencoding()
```

**Comment by SrinivasMushnoori** [comment]
Yes, this also returns `UTF-8`

```
(radical_stack)scm177@mcewan:~/RADICAL-LAB/RADICAL_ENTK_STACK/radical.entk$ python
Python 2.7.14 (default, Sep 18 2017, 00:00:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.getfilesystemencoding()
'UTF-8'
>>> 
```

**Comment by SrinivasMushnoori** [comment]
Okay I am ABSOLUTELY not sure what I did but I made something work. EnTK is not installed with the following stack: 
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/radical_stack

  radical.entk         : 0.70.0-v0.70.0@master
  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```

I ran the EnTK example `eop.py` twice as instructed and the client and agent sandboxes are attached for both runs. All this is on localhost.

Run 1: 
[Agent](https://github.com/radical-cybertools/radical.entk/files/3487160/run_1_agent.zip)
[Client](https://github.com/radical-cybertools/radical.entk/files/3487149/run_1_client.zip)


Run 2:
[Agent](https://github.com/radical-cybertools/radical.entk/files/3487163/run_2_agent.zip)
[Client](https://github.com/radical-cybertools/radical.entk/files/3487151/run_2_client.zip)

Both times, it fails with the same error, i.e. `resource allocation ended up in FAILED`

**Comment by mturilli** [comment]
Following our slack session, is this resolved now?

**Comment by SrinivasMushnoori** [comment]
Unfortunately, no. My last post still holds. The `resource allocation ended up in FAILED` error persists.

**Comment by mturilli** [comment]
Are you trying to run scripts locally? If so, did you setup passwordless ssh keys for your account? Can you enable DEBUG logging so that you can try to see at what level resource allocation fails?

**Comment by SrinivasMushnoori** [comment]
Yes, [here's the log file.](https://github.com/radical-cybertools/radical.entk/files/3487695/radical.log)
```
RADICAL_LOG_LVL=DEBUG
RADICAL_LOG_TGT=radical.log
```
I do have passwordless ssh to localhost setup, and I have developed all of repex by running on localhost. But this error is showing up on localhost as well as Bridges.

**Comment by mturilli** [comment]
In the attached log, I see the pilot/units have been running, some successfully some not. E.g.:
```
2019-08-09 13:47:09,101: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (G: \n25524.0:DONE:0   \n26093. ... UNNING: \n812.0:DONE:0   \n163)
2019-08-09 13:47:09,113: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (7.0:RUNNING: \n1637.0:DONE:0   ... 235.0:RUNNING: \n29235.0:DONE:)
2019-08-09 13:47:09,124: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (0   \n15365.0:RUNNING: \n15365 ...  \n22339.0:DONE:0   \n29935.0:)
2019-08-09 13:47:09,135: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (RUNNING: \n29935.0:DONE:0   \n ...  \n28397.0:RUNNING: \n28397.0:)
2019-08-09 13:47:09,145: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (DONE:0   \n28603.0:RUNNING: \n ... 62.0:DONE:0   \n21099.0:RUNNIN)
2019-08-09 13:47:09,155: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 1215] (G: \n21099.0:DONE:0   \n17240. ... DONE:0   \n25605.0:RUNNING: \n)
```

**Comment by SrinivasMushnoori** [comment]
I did a clean reboot of the machine to kill any processes running, but I still get the same error when I run [as seen here](https://github.com/radical-cybertools/radical.entk/files/3487781/radical.log)
 
Secondly, I am a little confused as to why a single EnTK job would instantiate multiple pilots.

**Comment by andre-merzky** [comment]
> In the attached log, I see the pilot/units have been running, some successfully some not. E.g.:
> 
> ```
> 2019-08-09 13:47:09,101: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (G: \n25524.0:DONE:0   \n26093. ... UNNING: \n812.0:DONE:0   \n163)
> 2019-08-09 13:47:09,113: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (7.0:RUNNING: \n1637.0:DONE:0   ... 235.0:RUNNING: \n29235.0:DONE:)
> 2019-08-09 13:47:09,124: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (0   \n15365.0:RUNNING: \n15365 ...  \n22339.0:DONE:0   \n29935.0:)
> 2019-08-09 13:47:09,135: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (RUNNING: \n29935.0:DONE:0   \n ...  \n28397.0:RUNNING: \n28397.0:)
> 2019-08-09 13:47:09,145: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 4095] (DONE:0   \n28603.0:RUNNING: \n ... 62.0:DONE:0   \n21099.0:RUNNIN)
> 2019-08-09 13:47:09,155: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  170] [ 1215] (G: \n21099.0:DONE:0   \n17240. ... DONE:0   \n25605.0:RUNNING: \n)
> ```

I don't think those are units: the SAGA layer is just looking through the past job history here, e.g. picks up state for old pilot jobs and the like.

**Comment by lee212** [comment]
@SrinivasMushnoori , I will close this ticket for now as it has not been updated for a while. If this was not resolved, please reopen and leave a comment.
