### ISSUE TITLE
Profiling EnTK workflow with online example script leads to parsing errors

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-cybertools/radical.entk#543]
### Problem Description

I'm trying to profile my EnTK workflow. I exactly followed the [online example script](https://radicalentk.readthedocs.io/en/stable/user_guide/profiling.html). When I run the script, I received the following error:

```
(venv_Predictability) wuh20@cheyenne4:~/github/pv-workflow/02_WeightOptimization> python ParseProfiling.py --dir re.session.cheyenne4.ib0.cheyenne.ucar.edu.wuh20.018661.0005/
Traceback (most recent call last):
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/entk/utils/prof_utils.py", line 83, in get_session_profile
    profiles = ru.read_profiles(profiles=profiles, sid=sid)
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/utils/profile.py", line 390, in read_profiles
    row[TIME] = float(row[TIME])
ValueError: could not convert string to float: '10.159.32.188:1612365490:1612365490:1612365490'
Traceback (most recent call last):
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/entk/utils/prof_utils.py", line 83, in get_session_profile
    profiles = ru.read_profiles(profiles=profiles, sid=sid)
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/utils/profile.py", line 390, in read_profiles
    row[TIME] = float(row[TIME])
ValueError: could not convert string to float: '10.159.32.188:1612365490:1612365490:1612365490'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "ParseProfiling.py", line 30, in <module>
    session = ra.Session(src=src, sid = sid, stype='radical.entk')
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/analytics/session.py", line 124, in __init__
    = reu.get_session_profile    (sid=sid, src=self._src)
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/entk/utils/prof_utils.py", line 102, in get_session_profile
    raise EnTKError('Error: %s' % ex) from ex
radical.entk.exceptions.EnTKError: Error: could not convert string to float: '10.159.32.188:1612365490:1612365490:1612365490'
```

### Setup

My EnTK stack is as follows:

```
  python               : /glade/u/home/wuh20/venv_Predictability/bin/python3
  pythonpath           : 
  version              : 3.7.9
  virtualenv           : /glade/u/home/wuh20/venv_Predictability
  radical.analytics    : 1.5.0
  radical.entk         : 1.5.8
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.11
  radical.saga         : 1.5.9
  radical.utils        : 1.5.9
```

Thank you!

**Comment by andre-merzky** [comment]
Apologies for the troubles - that problem has been fixed in radical.pilot, and the [fix](https://github.com/radical-cybertools/radical.pilot/commit/75a73a6bad04ea89ae39beae60927eb6c220c367) was released just yesterday.

**Comment by Weiming-Hu** [comment]
Thanks for the heads. I upgrade my radical.pilot, and now my stack looks like this:

```
(venv_Predictability) wuh20@cheyenne3:~/github/pv-workflow/02_WeightOptimization> radical-stack 

  python               : /glade/u/home/wuh20/venv_Predictability/bin/python3
  pythonpath           : 
  version              : 3.7.9
  virtualenv           : /glade/u/home/wuh20/venv_Predictability

  radical.analytics    : 1.5.0
  radical.entk         : 1.5.8
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.12
  radical.saga         : 1.5.9
  radical.utils        : 1.5.9
```

I still received an error though. Please see below.


```
(venv_Predictability) wuh20@cheyenne3:~/github/pv-workflow/02_WeightOptimization> python ParseProfiling.py --dir re.session.cheyenne3.ib0.cheyenne.ucar.edu.wuh20.018661.0008/
WARNING: profile "re.session.cheyenne3.ib0.cheyenne.ucar.edu.wuh20.018661.0008/umgr_reschedule_pubsub.prof" not correctly closed.
[ ....... Skip a log of warning messages like this ...... ]

#tasks   : 90

------------------------------------------------------------------------------
Time spent to create and submit the tasks
------------------------------------------------------------------------------

duration : 4.23

------------------------------------------------------------------------------
Time spent to execute the tasks
------------------------------------------------------------------------------

duration : 159.65

------------------------------------------------------------------------------
Time spent to process executed tasks
------------------------------------------------------------------------------

duration : 5.43

------------------------------------------------------------------------------
concurrent tasks in between SUBMITTING and EXECUTED states
------------------------------------------------------------------------------

Traceback (most recent call last):
  File "ParseProfiling.py", line 89, in <module>
    sampling=10)
  File "/glade/u/home/wuh20/venv_Predictability/lib/python3.7/site-packages/radical/analytics/session.py", line 858, in concurrency
    ret.append(t, val)
TypeError: append() takes exactly one argument (2 given)
```

**Comment by andre-merzky** [comment]
Thanks for reporting - that looks like an error in radical.analytics - we'll check it out.

**Comment by andre-merzky** [comment]
@Weiming-Hu : a fix for your last problem was merged in radical-cybertools/radical.analytics/pull/137, you may want to retry with the `devel` branch of RA.  Thanks!
